# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: F-Droid - Free and Open Source Android App Repository
header-title: F-Droid
description: >
  © 2010-2017 F-Droid Limited and Contributors
baseurl: "/fdroid-website" # the subpath of your site, e.g. /blog
url: "https://fdroid.gitlab.io" # the base hostname & protocol for your site
include:
  - "_pages"
collections:
  apps:
    output: true
gems:
  - jekyll-include-cache
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-feed
feed:
  path: feed
pagination:
  enabled: true